site_name: Finetune CLI
site_url: https://Abdur-azure.github.io/finetune_cli
repo_url: https://github.com/Abdur-azure/finetune_cli
repo_name: finetune_cli

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    - content.code.copy
  palette:
    scheme: default

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - codehilite
  - footnotes
  - tables

plugins:
  - search
